a = input("Введите свой возраст: ")
print(a)
b = input("Введите свой пол: ")
print(b)
c = input("Введите свое имя: ")
print(c)
d = input("Введите свой город: ")
print(d)
e = input("Введите свой класс: ")
print(e)